msrv = "1.41.1"
# PSBT API returns Self as an error type for an large-ish enum
large-error-threshold = 512
# A couple tests have huge tuples instead of structs. This is fixed
# in a later major rev. For now we just turn down the lint.
type-complexity-threshold = 1000
# Some internal compiler functions take a gazillion arguments. Again,
# this is fixed in a later major rev so just turn down the lint here.
too-many-arguments-threshold = 9
