on: [push, pull_request]

name: Continuous integration

jobs:
  Prepare:
    runs-on: ubuntu-24.04
    outputs:
      nightly_version: ${{ steps.read_toolchain.outputs.nightly_version }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Read nightly version"
        id: read_toolchain
        run: echo "nightly_version=$(cat nightly-version)" >> $GITHUB_OUTPUT

  Fuzz:
    name: Fuzz
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.58.0
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v2
      - name: Install hongfuzz dependancies
        run: sudo apt update && sudo apt install build-essential binutils-dev libunwind-dev libblocksruntime-dev liblzma-dev
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Running fuzzer
        env:
          DO_FUZZ: true
          DO_NO_STD: true
        run: ./contrib/test.sh

  Nightly:
    name: Nightly - Bench + Docs + Fmt
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v2
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ needs.Prepare.outputs.nightly_version }}
          override: true
      - name: Running benchmarks
        env:
          DO_BENCH: true
          DO_NO_STD: true
        run: ./contrib/test.sh
      - name: Building docs
        env:
          DO_DOCS: true
        run: ./contrib/test.sh
      - name: Running formatter
        env:
          DO_FMT: true
        run: ./contrib/test.sh

  Tests:
    name: Tests
    needs: Prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: stable
          - rust: beta
          - rust: ${{ needs.Prepare.outputs.nightly_version }}
          - rust: 1.41.1
          - rust: 1.47
            DO_NO_STD: true
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v2
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Running cargo
        env:
          DO_FEATURE_MATRIX: true
          DO_NO_STD: ${{ matrix.DO_NO_STD }}
        run: ./contrib/test.sh

  Embedded:
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        run: sudo apt update && sudo apt install -y qemu-system-arm gcc-arm-none-eabi
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ needs.Prepare.outputs.nightly_version }}
          override: true
          components: rust-src
          target: thumbv7m-none-eabi
      - name: Run
        env:
          RUSTFLAGS: "-C link-arg=-Tlink.x"
          CARGO_TARGET_THUMBV7M_NONE_EABI_RUNNER: "qemu-system-arm -cpu cortex-m3 -machine mps2-an385 -nographic -semihosting-config enable=on,target=native -kernel"
        run: cd embedded && cargo run --target thumbv7m-none-eabi --release
